config/routes.rb
Rails.application.routes.draw do

  root                                  to: 'employees#index'
  get       '/login',                   to: 'sessions#new'
  post      '/login',                   to: 'sessions#create'
  delete    '/logout',                  to: 'sessions#destroy'

  resources :employees
  resources :branches
  resources :departments

  # get       'departments',              to: 'departments#index'
  # get       'departments/show'
  # get       'departments/new',          to: 'departments#new'
  # post      'departments',              to: 'departments#create'
  # get       'departments/edit'
  # patch     'departments/update'
  # delete    'departments/destroy'

  # get       'branches',                 to: 'branches#index',       as: 'list_branch'
  # get       'branch/detail/:id',        to: 'branches#show',        as: 'show_branch'
  # get       'branch/new',               to: 'branches#new',         as: 'new_branch'
  # post      'branches',                 to: 'branches#create'
  # get       'branch/edit/:id',          to: 'branches#edit',        as: 'edit_branch'
  # patch     'branch/update/:id',        to: 'branches#update'
  # delete    'branch/destroy/:id',       to: 'branches#destroy',     as: 'delete_branch'

  # get       'employees',                to: 'employees#index',      as: 'list_employee'
  # get       'employee/detail/:id',      to: 'employees#show',       as: 'show_employee'
  # get       'employee/new',             to: 'employees#new',        as: 'new_employee'
  # post      'employees',                to: 'employees#create'
  # get       'employee/edit/:id',        to: 'employees#edit',       as: 'edit_employee'
  # patch     'employee/update/:id',      to: 'employees#update'
  # delete    'employee/delete/:id',      to: 'employees#destroy',    as: 'delete_employee'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord

  before_save   {self.email_address = email_address.downcase }
  validates     :first_name, presence: true, length: {maximum: 14}
  validates     :last_name, presence: true, length: {maximum: 14}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates     :email_address, presence: true, length: {maximum: 50}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates     :password, presence: true, length: {minumum: 6, maximum: 14}, allow_nil: true
  validates     :phone_number, numericality: {only_integer: true}
  validates     :department_id, presence: true
  validates     :branch_id, presence: true
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  before_filter :authorize

  def index
    @branches = Branch.all
  end

  def show
  end

  def new
  end

  def create
    branch = Branch.new(message_params)
    if branch.save
      flash[:success] = "New branch "+branch.branch_code+" saved"
      redirect_to branches_path
    else
      render new_branch_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def message_params
    params.require(:branch).permit(:branch_code, :address, :city, :phone_number)
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  before_filter :authorize

  def index
    @departments = Department.all
  end

  def show
  end

  def new
  end

  def create
    department = Department.new(message_params)
    if department.save
      flash[:success] = "New department "+department.department_name+" saved"
      redirect_to departments_path
    else
      render departments_new_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def message_params
    params.require(:department).permit(:department_code, :department_name, :description)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # Call authorization
  before_filter :authorize

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(message_params)
    if @employee.save
      flash[:success] = "New employee "+@employee.first_name+" "+@employee.last_name+" saved"
      redirect_to employees_path
    else
      render new_employee_path
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(message_params)
      flash[:success] = "Employee "+@employee.first_name+" "+@employee.last_name+" updated"
      redirect_to employees_path
    else
      render 'edit'
    end
  end

  def destroy
    employee = Employee.find(params[:id])
    if employee.destroy
      flash[:success] = "Employee "+employee.first_name+" "+employee.last_name+" deleted"
      redirect_to employees_path
    end
  end

  private
  def message_params
    params.require(:employee).permit(:first_name, :last_name, :email_address, :password, :password_confirmation, :phone_number, :department_id, :branch_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Render another layout for login page
  layout "login_layout"

  def new
  end

  def create
    employee = Employee.find_by(email_address: params[:session][:email].downcase)
    if employee && employee.authenticate(params[:session][:password])
      log_in employee
      redirect_to employees_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(employee)
    session[:employee_id] = employee.id
  end

  def current_employee
    @current_employee ||= Employee.find_by(id: session[:employee_id])
  end

  def logged_in?
    !current_employee.nil?
  end

  def authorize
    if not logged_in?
      redirect_to login_path
    end
  end

  def log_out
    session.delete(:employee_id)
    @current_employee = nil
  end
end

app/views/branches/create.html.erb
<h1>Branches#create</h1>
<p>Find me in app/views/branches/create.html.erb</p>

app/views/branches/destroy.html.erb
<h1>Branches#destroy</h1>
<p>Find me in app/views/branches/destroy.html.erb</p>

app/views/branches/edit.html.erb
<h1>Branches#edit</h1>
<p>Find me in app/views/branches/edit.html.erb</p>

app/views/branches/index.html.erb
<div class="row">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Adress</th>
      <th>City</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @branches.each do |branch| %>
    <tr>
      <td><%= branch.branch_code %></td>
      <td><%= branch.address %></td>
      <td><%= branch.city %></td>
      <td><%= branch.phone_number %></td>
    </tr>
    <% end %>
  </tbody>
</table
</div>

app/views/branches/new.html.erb
<div class="row">
  <div>
    <%= form_for(:branch, url: branches_path) do |f| %>
      <%= f.label :branch_code %>
      <%= f.text_field :branch_code, class: 'form-control' %>
      <%= f.label :address %>
      <%= f.text_area :address, class: 'form-control' %>
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
      <%= f.label :phone_number %>
      <%= f.telephone_field :phone_number, class: 'form-control'%>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/branches/show.html.erb
<h1>Branches#show</h1>
<p>Find me in app/views/branches/show.html.erb</p>

app/views/branches/update.html.erb
<h1>Branches#update</h1>
<p>Find me in app/views/branches/update.html.erb</p>

app/views/departments/create.html.erb
<h1>Departments#create</h1>
<p>Find me in app/views/departments/create.html.erb</p>

app/views/departments/destroy.html.erb
<h1>Departments#destroy</h1>
<p>Find me in app/views/departments/destroy.html.erb</p>

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<div class="row">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Dept. Name</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each do |dept| %>
    <tr>
      <td><%= dept.department_code %></td>
      <td><%= dept.department_name %></td>
    </tr>
    <% end %>
  </tbody>
</table
</div>

app/views/departments/new.html.erb
<div class="row">
  <div>
    <%= form_for(:department, url: departments_path) do |f| %>
      <%= f.label :department_code %>
      <%= f.text_field :department_code, class: 'form-control' %>
      <%= f.label :department_name %>
      <%= f.text_field :department_name, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/departments/show.html.erb
<h1>Departments#show</h1>
<p>Find me in app/views/departments/show.html.erb</p>

app/views/departments/update.html.erb
<h1>Departments#update</h1>
<p>Find me in app/views/departments/update.html.erb</p>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<h1>Edit</h1>
<div class="row">
  <div>
    <%= form_for(@employee) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.text_field :email_address, class: 'form-control' %>
      <%= f.label :phone %>
      <%= f.text_field :phone_number, class: 'form-control' %>
      <%= f.label :department %>
      <%= f.collection_select :department_id, Department.all, :id, :department_name, {prompt: true}, {class: "form-control"} %>
      <%= f.label :branch %>
      <%= f.collection_select :branch_id, Branch.all, :id, :city, {prompt: true}, {class: "form-control"} %>
      <%= f.submit "Save", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Department</th>
      <th>Branch</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.first_name+" "+employee.last_name %></td>
      <td><%= employee.email_address %></td>
      <td><%= employee.phone_number %></td>
      <td><%= Department.find_by(id: employee.department_id).department_name %></td>
      <td><%= Branch.find_by(id: employee.branch_id).city %></td>
      <td>
        <%= link_to "Edit", edit_employee_path(employee) %>
        <%= link_to "Delete", employee, method: :delete, data: {confirm: "Are you sure?"} %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>
<div class="row">
  <div>
    <%= form_for(@employee) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.text_field :email_address, class: 'form-control' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :confirm_password %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.label :phone %>
      <%= f.text_field :phone_number, class: 'form-control' %>
      <%= f.label :department %>
      <%= f.collection_select :department_id, Department.all, :id, :department_name, {prompt: true}, {class: "form-control"} %>
      <%= f.label :branch %>
      <%= f.collection_select :branch_id, Branch.all, :id, :city, {prompt: true}, {class: "form-control"} %>
      <%= f.submit "Save", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Find me in app/views/employees/show.html.erb</p>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/layouts/_flashing.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Employee", '#' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", employees_path(@current_employee) %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-pills nav-stacked nav-tree" data-toggle="nav-tree">
  <li>
    <%= link_to "Branches", branches_path %>
    <ul class="nav nav-pills nav-stacked nav-tree">
      <li><%= link_to "New branch", new_branch_path %></li>
    </ul>
    <%= link_to "Departments", departments_path %>
    <ul class="nav nav-pills nav-stacked nav-tree">
      <li><%= link_to "New department", new_department_path %></li>
    </ul>
    <%= link_to "Users", employees_path %>
    <ul class="nav nav-pills nav-stacked nav-tree">
      <li><%= link_to "New user", new_employee_path %></li>
    </ul>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myerprails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render 'layouts/navigation' %>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= render 'layouts/flashing' %>
          <%= yield %>
        </div>
      </div>
    </div>
    <% end %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myerprails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= render 'layouts/flashing' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@employee.errors.count, "error") %>.
    </div>
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>